### ISSUE TITLE
workshop vectortile example

### ISSUE THREAD

**Issue by nufosmatic** [openlayers/workshop#116]
The vectortile example references a URL which no longer exists:

examples/vectortile/map.js

```
  source: new VectorTileSource({
    attributions: [
      '<a href="http://www.openmaptiles.org/" target="_blank">&copy; OpenMapTiles</a>',
      '<a href="http://www.openstreetmap.org/about/" target="_blank">&copy; OpenStreetMap contributors</a>'
    ],
    format: new MVT(),
    **url: `https://free-{1-3}.tilehosting.com/data/v3/{z}/{x}/{y}.pbf.pict?key=${key}`,**
    maxZoom: 14

```

The free*.tilehosting.com was apparently updated to maps.tilehosting.com and now api.maptiler.com.

https://www.maptiler.com/news/2019/04/maptiler-cloud-infrastructure-upgrade/

However, api.maptiler.com/data returns only 404s. api.maptiler.com/streets apparently returns a tile, but in the wrong format. I can't find the right thing to replace /data/, assuming /data/ is the offending directory.

Everything works for me except this example. Thank you for the workshop.

**Comment by ahocevar** [comment]
Maybe @petrsloup can help update the example?

**Comment by petrsloup** [comment]
(Sorry for not jumping in sooner.)

I was just about to update the example, but I see it was already correctly updated by @mike-000 (https://github.com/openlayers/workshop/commit/4b7639d8f7c06e8263233aa1bf5619ea0f8565ea), so I guess this can be closed now.
