### ISSUE TITLE
Markup not visible in online version

### ISSUE THREAD

**Issue by geraldo** [openlayers/workshop#141]
Actually workshop doesn't show any markup, instead it shows a broken link with the first line of the markup. For example, in [Basics](https://openlayers.org/workshop/en/basics/) it shows up like this:

![image](https://user-images.githubusercontent.com/336371/156735908-d34096db-9bf2-46ad-b01c-1c2cd9533081.png)

When starting it up locally from last release workshop-6.8.1-en, it shows up correctly:

![image](https://user-images.githubusercontent.com/336371/156735980-14dd9f1d-5888-42bf-9be0-8a31e0220b93.png)

**Comment by ahocevar** [comment]
Thanks for reporting this, @geraldo.

@tschaub I think this was introduced with your recent changes. It looks like the `[import](path/to/file)` syntax does not work any more. But I don't find anything about this in the Honkit documentation. Unfortunately I did not have time to investigate more thoroughly. Maybe you can take a look?

**Comment by tschaub** [comment]
It’s back again now.
