### ISSUE TITLE
maps.opengeo.org/geowebcache/service/wms is down

### ISSUE THREAD

**Issue by elemoine** [openlayers/workshop#29]
A lot of the workshop examples rely on maps.opengeo.org/geowebcache/service/wms, which is down currently. For example, this [request](http://maps.opengeo.org/geowebcache/service/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=bluemarble&WIDTH=256&HEIGHT=256&SRS=EPSG%3A4326&STYLES=&BBOX=0%2C-90%2C180%2C90) returns an "nginx error" web page.

@ahocevar, @bartvde, should we use another geowebcache instance?

**Comment by ahocevar** [comment]
Maybe better to use http://demo.opengeo.org/geoserver/wms, which is a real WMS and not just a WMS-C endpoint.

**Comment by elemoine** [comment]
Ok, thanks.

**Comment by elemoine** [comment]
The geowebcache service is back. So I am not sure which one we should rely on. The geoserver service may be a  safer choice but it's probably also slower.

**Comment by bartvde** [comment]
It has been intermittent for a while, so I would not rely on it. Actually the workshop @marcjansen did a FOSSGIS was ruined quite a bit because we had to switch to a different tile server.

**Comment by elemoine** [comment]
@bartvde, are you saying you would use http://demo.opengeo.org/geoserver/wms, as suggested by Andreas?

**Comment by bartvde** [comment]
Or any other tile server that might be more reliable.

**Comment by elemoine** [comment]
I just realized that demo.opengeo.org/geoserver/wms does not have the "openstreetmap" layer that the geowebcache service has, and that we use in the workshop.

**Comment by ahocevar** [comment]
Previously, I used the 'nasa:bluemarble' layer instead.

**Comment by elemoine** [comment]
It's just that the workshop tells the participate to change from bluemarble to openstreetmap as an exercise. But we can obviously use another layer if geoserver includes other "world" layer.

**Comment by ahocevar** [comment]
'osm:osm' is an OSM layer that's available on demo.opengeo.org. So that could work maybe.
