### ISSUE TITLE
Why use loader.js?

### ISSUE THREAD

**Issue by elemoine** [openlayers/workshop#33]
Thinking about it I wonder why we make our participants use `loader.js` instead of a `ol.js` (the full OpenLayers build)? The problems I see with `loader.js`:
- it's not how most people would use OpenLayers
- it takes a lot of time each time you reload an example page

I am not sure I want to change this now though.

**Comment by marcjansen** [comment]
Generally I would also prefer not to use loader.js.

**Comment by elemoine** [comment]
Old and irrelevant issue. Closing.
