### ISSUE TITLE
firefox fail

### ISSUE THREAD

**Issue by warb12** [openlayers/workshop#52]
First Example loads in chrome , not in Firefox.

![firefoxfail](https://cloud.githubusercontent.com/assets/1297978/15449557/de6731ec-1f4e-11e6-9ce0-f1893a9ab4b1.png)

**Comment by marcjansen** [comment]
Ouch. We'll investigate. Hoping this is just a quirk. Thanks for reporting.

**Comment by marcjansen** [comment]
If this isn't a network thingy, we'll need the output of the console (`F12` and reload, please).

**Comment by warb12** [comment]
I see this in the console:

ReferenceError: ol is not defined

var map = new ol.Map({


Holy crap, what's all those scripts loaded into the header? ol should be
there somewhere!

**Comment by marcjansen** [comment]
Loads fine in FF 48 (Linux), closing.

![image](https://cloud.githubusercontent.com/assets/227934/17697534/ac661d74-63b5-11e6-9d88-0af2cec36966.png)

Please reopen if the problem persists.
