### ISSUE TITLE
Bing API key?

### ISSUE THREAD

**Issue by tsauerwein** [openlayers/workshop#62]
The API key given in the workshop is `'<Your Bing Maps Key Here>'`:
https://github.com/openlayers/workshop/blob/master/src/en/layers/proprietary.md#tasks

This does not work. :)

**Comment by bartvde** [comment]
See: https://github.com/openlayers/workshop/pull/44 for context why this was done this way

**Comment by tsauerwein** [comment]
Ok, thanks. How will we do in the workshop? @marcjansen?

**Comment by bartvde** [comment]
I guess we'll need to change the ZIP file before we distribute it on the machines?

**Comment by marcjansen** [comment]
Nah. We'll just sign up or write one at the whiteboard.

Also we won't use the zip from a downöload, but instead I have already installed a clone of the workshop repo. Before the workshop we'll do the following on all machines:

```
git checkout tags/v3.16.0 -b v3.16.0 && npm install
```

**Comment by tsauerwein** [comment]
> Nah. We'll just sign up or write one at the whiteboard.

We write a 30 chars key on a whiteboard and let the students copy this key? :D 

But we could create a short link to some page where a key is stored.

**Comment by bartvde** [comment]
yes and if they fail at the exercise they will have to leave the room ;-)

**Comment by marcjansen** [comment]
Not even sure if there is a whiteboard :see_no_evil:

**Comment by marcjansen** [comment]
We jsut point them to this closed PR :wine_glass:

**Comment by bartvde** [comment]
@marcjansen btw should we change the WMS service in the exercise to avoid the trouble we had at FOSSGIS ;-) ?

**Comment by marcjansen** [comment]
I don't remember any trouble. Please change at will, but in order to be 
presentable we need to have a release

**Comment by bartvde** [comment]
The boundlessgeo demo server was down at FOSSGIS in Munster back then

**Comment by bartvde** [comment]
I'm sure @chrismayer remembers?

**Comment by tsauerwein** [comment]
Ok, I registered an API key for the workshop. And it's easily copy&pastable via this URL: http://bit.ly/ol3-workshop

**Comment by chrismayer** [comment]
>The boundlessgeo demo server was down at FOSSGIS in Munster back then

Yes, @bartvde the WMS wasn't accesible in the FOSSGIS 2015 workshop (for whatever reason).

**Comment by bartvde** [comment]
I'm glad to hear my memory is better these days than of someone else @marcjansen :-)
