### ISSUE TITLE
map source code

### ISSUE THREAD

**Issue by ademus** [openlayers/workshop#75]
is there's a way to retrieve code sources files of this nice map (with spots and popup) :
[https://render.githubusercontent.com/view/geojson....](https://render.githubusercontent.com/view/geojson?commit=84cab52af453a6566a03d999b9c8d3cc2723119f&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6f70656e6c61796572732f776f726b73686f702f383463616235326166343533613635363661303364393939623963386433636332373233313139662f7372632f66722f646174612f6c61796572732f376461792d4d322e352e6a736f6e&nwo=openlayers%2Fworkshop&path=src%2Ffr%2Fdata%2Flayers%2F7day-M2.5.json&repository_id=13985501#dcd413c9-3379-498d-86f0-a3a59f122a3d)
or 
[https://github.com/openlayers/workshop....](https://github.com/openlayers/workshop/blob/master/src/fr/data/layers/7day-M2.5.json)

??? 
Thanks a lot

**Comment by bartvde** [comment]
you should ask github this, it's their geojson renderer based on mapbox code

**Comment by bartvde** [comment]
See also https://help.github.com/articles/mapping-geojson-files-on-github/ and maybe you can ping @benbalter for more info, I know he has been involved in this

**Comment by ademus** [comment]
Thank u very much man !
