### ISSUE TITLE
Geoserver hosted by demo.opengeo.org is down for a long time (503 error)

### ISSUE THREAD

**Issue by ranophoenix** [openlayers/workshop#76]
Hi,

Why not change to https://ahocevar.com/geoserver/ (the same server used by OpenLayers' examples)?

I'd be happy to create the patch with the changes.

Thanks in advance.

**Comment by fredj** [comment]
hi, the server was changed to https://ahocevar.com/ in #72

**Comment by ranophoenix** [comment]
Sorry, I was using version 4.0.1 instead of 4.0.2-alpha.1. Thanks!
