### ISSUE TITLE
Uncorrect phrasing in doc/en/basics/popup.md?!

### ISSUE THREAD

**Issue by ThomasG77** [openlayers/workshop#82]
In https://github.com/openlayers/workshop/blob/master/doc/en/basics/popup.md, it seems there is a missing "to"

> In addition to the css, we also need to add the markup for the container the body of our `index.html`:

should be

> In addition to the css, we also need to add the markup for the container to the body of our `index.html`:

As I'm not a native English speaker, I may be wrong. Thanks for your feedback

**Comment by fredj** [comment]
You're right, a "to" is missing

**Comment by ThomasG77** [comment]
Made a PR :)
