### ISSUE TITLE
4.3.2-en nmp start fails on windows - backslash iso forward slash

### ISSUE THREAD

**Issue by jdegraef** [openlayers/workshop#88]
npm start

> openlayers-workshop@4.3.2-en start C:\filefuif\workshop-4.3.2-en
> mkdir -p doc/_book && npm run doc:serve

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openlayers-workshop@4.3.2-en start: `mkdir -p doc/_book && npm run doc:serve`
npm ERR! Exit status 1
npm ERR!

running the commands manually with a backslash i.e.
mkdir -p doc**\**_book
does the job. 
(it starts on port 4000 iso 3000 and the link from the intro doc is wrong too)

**Comment by marcjansen** [comment]
We  could use `[mkdirp](https://www.npmjs.com/package/mkdirp)`, that should work everywhere. PR welcome.

**Comment by jdegraef** [comment]
also, it serves up a doc language selection page on port 4000, So I'm stuck at the very first 'basics' part of the workshop. Where//How to serve up my index.html and main.js with node?
(according to the docs the npn start command is supposed to start a dev server as well, but it seems to start only a doc server?) tnx for any help.

**Comment by ahocevar** [comment]
@jdegraef When working with the examples, you should start the dev server from the `src/en` directory.

**Comment by jdegraef** [comment]
Alright, i had to do an npm install first, but now I seem to be up and running!
Maybe I missed it but I couldn't find a reference in the docs about navigating into src/en 

tnx, time to go play!

**Comment by SteveLowman** [comment]
It is quite frustrating. I went to the OpenLayers workshop an FOSS4GUK 2018 and did this with my work computer. Now, trying at home, I cannot set up the development environment. I had this problem, and tried the solution of cd to the src\en folder. I can get the popup (in Chrome but not in Firefox), but nothing else will work. Perhaps I may try the previous version 4.3.1

**Comment by marcjansen** [comment]
This workshop will be presented during the German FOSSGIS next week by @ahocevar, @chrismayer and me... in preparation we might be able to sort thie mentioned problems out. Stay tuned a bit, please

**Comment by ahocevar** [comment]
@SteveLowman @jdegraef To clarify: workshop attendees should download a workshop release from the [releases page](https://github.com/openlayers/workshop/releases). This repository with its workshop root is for workshop authors.

**Comment by SteveLowman** [comment]
Thank you. I think what confused me was at [http://uk.osgeo.org/foss4guk2018/workshops.html#creating-web-maps-using-openlayers](http://uk.osgeo.org/foss4guk2018/workshops.html#creating-web-maps-using-openlayers), where it says "Download the latest version of openlayers-workshop-en.zip from workshop release", I read "latest version of ..." but neglected to take note of "openlayers-workshop-en.zip", so the latest version was 4.3.2 at the top of the Releases page with the green label stating "Latest Release", and I downloaded the "source code.zip" from there.

It was my mistake. The only way I can suggest to help people avoid this mistake is to say something like, "Download the 'openlayers-workshop-en.zip. Do not download 'source code.zip'!"
