### ISSUE TITLE
Import required for static style

### ISSUE THREAD

**Issue by philippeleloir** [openlayers/workshop#96]
Hello! In the 'Making it look nice' section of the workshop, the requirement for "import {Fill, Stroke, Style} from 'ol/style';" comes only in the 'Styling based on geometry area' subsection, but it is required to run the 'Static style' subsection.

Excellent work btw :)

**Comment by marcjansen** [comment]
Thanks. Can you come up with a pull request? That would be nice.

**Comment by philippeleloir** [comment]
Ok!

**Comment by marcjansen** [comment]
Fixed in #97.
